executable = cluster_sub/crowdpose_prep.sh
arguments = $(Process)
error = condor_logs/25.10-eft_crowdpose/$(Cluster).$(Process).err
output = condor_logs/25.10-eft_crowdpose/$(Cluster).$(Process).out
log = condor_logs/25.10-eft_crowdpose/$(Cluster).$(Process).log
request_memory = 32000
request_cpus=4
request_gpus=1
requirements=CUDADeviceName=="Tesla V100-PCIE-16GB" || CUDADeviceName=="Tesla V100-PCIE-32GB" || CUDADeviceName=="Tesla V100-SXM2-32GB" || CUDADeviceName=="Quadro RTX 6000" || CUDADeviceName=="GeForce RTX 2080 Ti"
queue 34