executable = /home/mkocabas/miniconda3/bin/python
arguments = scripts/figure_generator.py coco $(Process)
error = condor_logs/blender_coco/$(Cluster).$(Process).err
output = condor_logs/blender_coco/$(Cluster).$(Process).out
log = condor_logs/blender_coco/$(Cluster).$(Process).log
request_memory = 16000
request_cpus=4
request_gpus=1
requirements=CUDADeviceName=="Tesla V100-PCIE-16GB" || CUDADeviceName=="Tesla V100-PCIE-32GB" || CUDADeviceName=="Tesla V100-SXM2-32GB" || CUDADeviceName=="Quadro RTX 6000" || CUDADeviceName=="GeForce RTX 2080 Ti"
queue 167